# SPDX-FileCopyrightText: Copyright © 2024-2026 Caleb Cushing
#
# SPDX-License-Identifier: CC0-1.0

# common
"Makefile":
  - &mit "reuse annotate --license 'MIT' --copyright 'Caleb Cushing' --copyright-prefix spdx-string-symbol --merge-copyrights --fallback-dot-license"
"{.config/git/hooks/*,*.sh}":
  - "reuse annotate --license 'MIT' --copyright 'Caleb Cushing' --copyright-prefix spdx-string-symbol --merge-copyrights --style python"
  - &prettier "prettier --cache --ignore-unknown --write"
"*.{md,adoc}":
  - "reuse annotate --license 'CC-BY-NC-SA-4.0' --copyright 'Caleb Cushing' --copyright-prefix spdx-string-symbol --merge-copyrights"
  - *prettier
"*.{xml,yml,yaml,properties,toml,json5,js}":
  - &cc0 "reuse annotate --license 'CC0-1.0' --copyright 'Caleb Cushing' --copyright-prefix spdx-string-symbol --merge-copyrights --fallback-dot-license"
  - *prettier
"*.properties":
  - "reuse annotate --license 'CC0-1.0' --copyright 'Caleb Cushing' --merge-copyrights"
  - *prettier
".{editorconfig,gitattributes,mailmap,*ignore}":
  - *cc0
  - *prettier
"!(package).json":
  - *cc0
  - *prettier
"package.json":
  - *mit
  - *prettier
"*.gradle.kts":
  - *mit
  - ktlint --format
# unique
"*.java":
  - "reuse annotate --license 'GPL-3.0-or-later WITH Classpath-exception-2.0' --copyright 'Caleb Cushing' --copyright-prefix spdx-string-symbol --merge-copyrights"
  - *prettier
