# SPDX-FileCopyrightText: Copyright © 2024 Caleb Cushing
#
# SPDX-License-Identifier: CC0-1.0
# SPDX-License-Identifier: MIT

printWidth: 120
plugins:
  - "@prettier/plugin-xml"
  - prettier-plugin-properties
  - prettier-plugin-java
  - prettier-plugin-toml
  - prettier-plugin-sh
