# SPDX-FileCopyrightText: Copyright © 2024 - 2025 Caleb Cushing
#
# SPDX-License-Identifier: CC0-1.0

version = 1
[[annotations]]
path = "**/*.lockfile"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
[[annotations]]
path = "**/requirements.txt"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "yarn.lock"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
[[annotations]]
path = ".tool-versions"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
[[annotations]]
path = "gradle/wrapper/gradle-wrapper.jar"
SPDX-FileCopyrightText = "See MANIFEST.MF in jar"
SPDX-License-Identifier = "Apache-2.0"
[[annotations]]
path = "gradle/wrapper/gradle-wrapper.properties"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
