# SPDX-FileCopyrightText: Copyright © 2024-2026 Caleb Cushing
#
# SPDX-License-Identifier: CC0-1.0

[versions]
ep = "2.+"
convention = "0.17.+"
immutables = "2.+"
junit = "6.+"

[libraries]
assertj = "org.assertj:assertj-core:3.+"
commons-lang = "org.apache.commons:commons-lang3:3.+"
errorprone-annotations = { module = "com.google.errorprone:error_prone_annotations", version.ref = "ep" }
errorprone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "ep" }
errorprone-nullaway = "com.uber.nullaway:nullaway:0.+"
guava = "com.google.guava:guava:+"
immutables-annotate = { module = "org.immutables:annotate" }
immutables-annotations = { module = "org.immutables:value-annotations" }
immutables-bom = { module = "org.immutables:bom", version.ref = "immutables" }
immutables-builder = { module = "org.immutables:builder" }
immutables-core = { module = "org.immutables:value" }
java-tools = "com.xenoterracide:tools:0.+"
jgit = "org.eclipse.jgit:org.eclipse.jgit:7.+"
jspecify = "org.jspecify:jspecify:1.+"
junit-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-parameters = { module = "org.junit.jupiter:junit-jupiter-params" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }
maven-artifact = "org.apache.maven:maven-artifact:3.+"
plugin-convention-checkstyle = { module = "com.xenoterracide.gradle.convention:checkstyle", version.ref = "convention" }
plugin-convention-compile = { module = "com.xenoterracide.gradle.convention:compile", version.ref = "convention" }
plugin-convention-coverage = { module = "com.xenoterracide.gradle.convention:coverage", version.ref = "convention" }
plugin-convention-javadoc = { module = "com.xenoterracide.gradle.convention:javadoc", version.ref = "convention" }
plugin-convention-publish = { module = "com.xenoterracide.gradle.convention:publish", version.ref = "convention" }
plugin-convention-spotbugs = { module = "com.xenoterracide.gradle.convention:spotbugs", version.ref = "convention" }
plugin-convention-test = { module = "com.xenoterracide.gradle.convention:test", version.ref = "convention" }
plugin-dependency-analysis = { module = "com.autonomousapps:dependency-analysis-gradle-plugin", version = "3.+" }
plugin-errorprone = "net.ltgt.gradle:gradle-errorprone-plugin:5.+"
plugin-gradle-plugin-publish = "com.gradle.publish:plugin-publish-plugin:2.+"
semver = "org.semver4j:semver4j:6.+"
spotbugs = "com.github.spotbugs:spotbugs:4.+"
vavr = "io.vavr:vavr:1.+"

[bundles]
ep = ["errorprone-core", "errorprone-nullaway"]
immutables = ["immutables-annotations", "immutables-builder", "immutables-annotate"]
test-impl = ["junit-api", "assertj", "junit-parameters"]
test-runtime = ["junit-engine", "junit-launcher"]

[plugins]
dependency-analysis = { id = "com.autonomousapps.dependency-analysis" }
shadow = { id = "com.gradleup.shadow", version = "9.+" }
semver = { id = "com.xenoterracide.gradle.semver", version = "0.+" }
