# SPDX-FileCopyrightText: Copyright © 2024-2026 Caleb Cushing
#
# SPDX-License-Identifier: MIT
name: precommit
on: [push, workflow_call]
jobs:
  license:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - &checkout-step
        uses: actions/checkout@v6.0.2
        with:
          ref: ${{ github.ref }}
          filter: "blob:none"
          fetch-depth: 0
      - uses: actions/setup-python@v6.2.0
        with:
          python-version: "3"
      - run: pip install -r requirements.txt --require-hashes
      - run: reuse lint
  format:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - *checkout-step
      - uses: actions/setup-node@v6.2.0
        with:
          node-version: 24
          package-manager-cache: false
      - run: corepack enable
      - uses: actions/setup-node@v6.2.0
        with:
          node-version: 24
          cache: "yarn"
      - run: yarn install --immutable --inline-builds --check-resolutions
      - run: yarn exec prettier --ignore-unknown --check '**'
