# SPDX-FileCopyrightText: Copyright © 2024-2026 Caleb Cushing
#
# SPDX-License-Identifier: CC0-1.0

name: precommit
on: [push, workflow_call]
jobs:
  license:
    uses: xenoterracide/github/.github/workflows/license.yml@4638b8c9a7a42c42d70da79ed3491a301433a6a1
  format:
    uses: xenoterracide/github/.github/workflows/format.yml@4638b8c9a7a42c42d70da79ed3491a301433a6a1
  format-kotlin:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-java@v5.2.0
        with:
          distribution: temurin
          java-version: 21
      - uses: asdf-vm/actions/plugins-add@v4.0.1
      - run: asdf install ktlint
      - run: ktlint '*.gradle.kts' '**/*.gradle.kts'
