# SPDX-FileCopyrightText: Copyright © 2024-2026 Caleb Cushing
#
# SPDX-License-Identifier: CC0-1.0

name: update-java
on:
  schedule:
    - cron: "0 3 * * *"
  push:
    branches:
      - "ci/auto-update**"
jobs:
  update-java:
    uses: xenoterracide/github/.github/workflows/update-java.yml@4638b8c9a7a42c42d70da79ed3491a301433a6a1
    secrets:
      gradle_encryption_key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      merge_pat: ${{ secrets.GH_MERGE_PAT }}
    permissions:
      contents: read
      packages: read
      pull-requests: write
