# SPDX-FileCopyrightText: Copyright © 2024-2026 Caleb Cushing
#
# SPDX-License-Identifier: CC0-1.0

name: update-java
on:
  schedule:
    - cron: "0 3 * * *"

jobs:
  update-java:
    uses: xenoterracide/github/.github/workflows/update-java.yml@develop
